### ISSUE TITLE
unroll values like uland does

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/uland-ssr#2]
In [this issue](https://github.com/WebReflection/uland/issues/14) it came up that all *uland* values are resolved right away, like it is for *uhtml-ssr*.

However, this means that hooks cannot actually work the same way these do in *uland*, so that this module becomes less portable/interesting when it comes to SSR.

## TODO

- [x] implement `html` (`svg` can be just an alias) so that values can be parsed later on
- [x] use original `html` (`svg` could be the same) to resolve *holes* once "*unrolled*"
- [x] add the ability to unroll *Hook* instances ~~and provide an internal `Hole` too~~
- [x] perform similar dance the *uland* does, ignoring all caches around, as these are not needed
- [x] use the same uland mechanism to produce the *async* export

**Comment by WebReflection** [comment]
[This MR](https://github.com/WebReflection/uland-ssr/pull/3) fixed this issue, and *uland-ssr* has now been published.
